### PR TITLE
Dependency search accuracy and performance improvement

### PR DESCRIPTION
**Pull request by NeVeSpl**
This one is huge.  

### Key points 
- 5x less allocated memory
- 2x better performance
- all performance gains were achieved by simplifying code, none of micro-optimization that would defy code abstraction was used
- a lot of new unit tests, 56 of them are failing on the main branch
- arrays, generics, nested types, pointers, byRef are now first-class citizens and fully semantically recognized, thus if one wants to search for ```Dependecy[]``` he or she will get matches only on an array of ```Dependency``` and not a single variable of ```Dependency``` type . One remark: all multidimensional arrays regardless of their rank are recognized as the same, therefore ```Dependency[,] == Dependency[,,]```
- fully qualified names are now recognized, so (almost) everything specified as ```typeof(GenericDependecy<int>).FullName``` should be detected correctly, but still may be some corner cases with more exotic combinations that are not detected correctly 
- ```TypeDefinition.Resolve()``` is not used anymore by dependency search, thus one can test single dll without fear of getting rather a nasty exception about missing assembly
- ```Types``` class returns nested types as separate from the parent class. Dependency search, now, also behaves the same way. Dependencies found in nested classes are not counted any more as dependencies for parent type (unless it is a compiler-generated nested class).

### Fixed problems

1) all attributes were not checked for the presence of dependency, now attributes are checked for: class, field, event, property, method, method parameter, method return
```csharp
[AttributeDependency()]
public class AttributeOnClass
{
}
```
2) dependencies were not detected in generic variables
```csharp
public Foo()
{
    List<ExampleDependency> test = null;           
}
```
3) dependencies were not detected in a generic field
```csharp
public class Foo
{
    public List<ExampleDependency> test;
}
```
4) all implemented interfaces by type were not checked
```csharp
class Foo: InterfaceDependecy
{
}
```
5) generic constraints were not checked at all
```csharp
public class Foo<T>  where T : ExampleDependency, new() 
{
}
```

6) generic type parameters (T) were detected as dependency
```csharp
public class Foo<T>  
{
}
```

7) dependencies were not detected in arrays
```csharp
public void Foo()
{
    ExampleDependency[] test1 = null;    
    ExampleDependency[,] test2= null;      
    ExampleDependency[][] test3= null;        
}
```

8) it was not posible to search for dependecy which is:
- a closed generic
- a nested type
- a multidimensional array
```csharp
Types.FromFile(@"Foo.dll").ShouldNot().HaveDependencyOnAny(
   typeof(GenericDependecy<int>).FullName,                            
   typeof(NestedDependencyTree.NestedLevel1.NestedDependency).FullName,
   typeof(ExampleDependency[,]).FullName,
).GetResult();
```

9) dependencies were not detected in types passed by reference
```csharp
public void Foo(ref ExampleDependency foo)
{
        
}
```

10) dependencies were not detected in pointers
```csharp
public void Foo()
{
    unsafe
    {
       StructDependency* test = null;
    }  
}
```

### Major changes in code
- [src/NetArchTest.Rules/Dependencies/TypeParser.cs](https://github.com/BenMorris/NetArchTest/pull/62/files#diff-a01a82844ff038b47d4fc267273b3137)
This new class allows parsing fully qualified names that are returned from ```typeof(T).FullName```.  Parsing FQN correctly is not an easy job, but luckily Mono.Cecil already has a class that does that, but here the luck ends because the class is internal, thus reflection for a rescue.  I am not proud of it, but it works.

- [src/NetArchTest.Rules/Dependencies/DataStructures/TypeReferenceTree.cs](https://github.com/BenMorris/NetArchTest/pull/62/files#diff-29707ca0dec9b40f5f35d9c147cc0c26)
Another new class. It is very similar to already existing NamespaceTree. The difference is this one does not allocate any new string instance. It uses only strings that are already allocated by Mono.Cecil. To find value in the tree, it does not have to split strings, which makes it much more faster than NamespaceTree. It is used as a cache for calls to NamespaceTree. Why not use Dictionary<string, string[]> as the cache with ```TypeReference.FullName``` used as a key one may ask? The problem is in that Mono.Cecil does not cache FullName for complex types like generics and arrays, and every call for FullName creates new StringBuilder behind the scene.

- [src/NetArchTest.Rules/Dependencies/TypeDefinitionCheckingContext.cs](https://github.com/BenMorris/NetArchTest/pull/62/files#diff-b1bf330c1a9c241f4c5fed6c14b7f3b6)
All code related to checking single type was extracted to this class, it greatly simplified code and allowed to get rid of a few not necessary any more data structures and methods. ```TypeReference``` is now searched for dependencies in only one place, there is no more possible situation than in one fragment of code generic will be recognized correctly and in other not. Circular checks and calling ```TypeReference.Resolve()``` were eliminated. All missing checks were added: attributes, implemented interfaces, generic constraints, arrays.

- [src/NetArchTest.Rules/Dependencies/NamespaceTree.cs → src/NetArchTest.Rules/Dependencies/DataStructures/NamespaceTree.cs](https://github.com/BenMorris/NetArchTest/pull/62/files#diff-50c7972364256a8f3d076733c79e9ca7)
The biggest change to this tree is the addition of the new overloaded method ```GetAllMatchingNames(TypeReference reference)```. It not only eliminates the need for using ```TypeReference.FullName```, but also ensure that the full name of the type will be split exactly as the one returned from TypeParser. Also, the previous implementation did not return full name of the found match, which could lead to ambiguity since for two different types with the same name but different namespace, result would be the same (e.g. : SomeNamespace.SomeType -> SomeType, DifferentNamespace.SomeType -> SomeType); 

- [src/NetArchTest.Rules/Dependencies/DependencySearch.cs](https://github.com/BenMorris/NetArchTest/pull/62/files#diff-9ae95e840fe1c82a5eca803bd4f9b53d)
It is a very simple class now after moving all checkings to ```TypeDefinitionCheckingContext``` and deciding if the type was found to ```SearchDefinition ```. It only setups SearchDefinition and executes the search.

- [src/NetArchTest.Rules/Dependencies/SearchDefinition.cs](https://github.com/BenMorris/NetArchTest/pull/62/files#diff-4132a58cf5742e507d645f8676472247)
It only has two responsibilities now: deciding if a type was found and doing a search in the ```NamespaceTree```. Result of the search is now stored per type in ```TypeDefinitionCheckingContext``` so ugly ```Dictionary<string, HashSet<string>> _found``` was eliminated, also ```HashSet<string> _checked;``` is not needed any more since after small correction circular checks are not possible at all.

- [src/NetArchTest.Rules/Types.cs](https://github.com/BenMorris/NetArchTest/pull/62/files#diff-b5aa993c8ee82490734afdd9a25f0640)
Only one change in the area outside of dependency search. Using queue is not necessary to load all types, it was very visible during code profiling so I couldn't resist myself from eliminating it.

All the above classes do not base on string.split to extract or match type any more. They do that in a semantic way recognizing different language structures. There are only two simplifications:

- ```Dependency[,] == Dependency[,,]``` - all multidimensional arrays regardless of their rank are recognized as the same
- namespace, type's name and nested class are not distinguishable:
``` SomeNameSpace.Type.Nested == SomeNameSpace.Type+Nested``` where we have
```namespace(SomeNameSpace).namespace(Type).type_name(Nested) == namespace(SomeNameSpace).type_name(Type).nested_type_name(Nested)```

### Benchmarks

Benchmarks were done on two projects and test suite. 
Project 1 - an exemplary project which has about 100 types
Project 2 - real production project which has about 1100 types

#### Project 1:

|    Method |      Mean |    Error |   StdDev | Rank |      Gen 0 |      Gen 1 |     Gen 2 | Allocated |
|---------- |----------:|---------:|---------:|-----:|-----------:|-----------:|----------:|----------:|
| Before |  27.73 ms | 0.113 ms | 0.106 ms |    1 |  3312.5000 |  1656.2500 | 1000.0000 |  18.78 MB |
| After |  11.94 ms | 0.179 ms | 0.176 ms |    1 |   578.1250 |  265.6250 |         - |   3.51 MB |

Improvement
Time: 2.32x
Memory: 5.35x

#### Project 2:

|    Method |      Mean |    Error |   StdDev | Rank |      Gen 0 |      Gen 1 |     Gen 2 | Allocated |
|---------- |----------:|---------:|---------:|-----:|-----------:|-----------:|----------:|----------:|
| Before | 674.57 ms | 4.942 ms | 4.381 ms |    2 | 69000.0000 | 25000.0000 | 5000.0000 | 401.78 MB |
| After | 345.30 ms | 1.642 ms | 1.536 ms |    2 | 11000.0000 | 5000.0000 | 2000.0000 |  63.91 MB |

Improvement
Time: 1.95x 
Memory: 6.28x

#### Test suite:

| Tests | Before pull request|  After pull request| Time Improvement |
| ------------- |:-------------:| -----:|-----:|
| All(289)                                           |  22.2 s  |  6.7s |  3.31x |
| Time to search all dependencies    | 12.0s    |   2.3s | 5.21x |
| Time to search any dependency     | 6.2s     |  1.8s  | 3.44x |

### CODE REVIEW

**Comment by NeVeSpl** [comment]
I have added three more commits, this time focusing on rewriting SearchDefinition class.  Times improved again.

| Tests |   New one |
| ----------- |:-------------:| 
| All(264)      |     9.8s |
| Time to search all dependencies  |  6.4s |
| Time to search any dependency |  714ms  |

I have also done benchmark on small project ~150 classes.

|    Method |     Mean |     Error |    StdDev |     Gen 0 |    Gen 1 | Gen 2 | Allocated |
|---------- |---------:|----------:|----------:|---------:|---------:|------:|----------:|
| After this pull request | 8.821 ms | 0.0681 ms | 0.0568 ms | 500.0000 | 250.0000 |     - |   3.03 MB |
| Before this pull request | 22.27 ms | 0.317 ms | 0.296 ms |  2812.5000 | 1968.7500 | 1000.0000 |  14.69 MB |

**Comment by NeVeSpl** [comment]
Another commit focusing on improving performance, current results:

| Tests |   New one |
| ----------- |:-------------:| 
| All(264)      |     6.7s |
| Time to search all dependencies  |  3.2s |
| Time to search any dependency |  685ms  |



|    Method |     Mean |     Error |    StdDev |     Gen 0 |    Gen 1 | Gen 2 | Allocated |
|---------- |---------:|----------:|----------:|---------:|---------:|------:|----------:|
| After this pull request | 8.149 ms | 0.0559 ms | 0.0495 ms |  406.2500 | 203.1250 |     - |   2.44 MB |
| Before this pull request | 22.27 ms | 0.317 ms | 0.296 ms |  2812.5000 | 1968.7500 | 1000.0000 |  14.69 MB |

**Comment by NeVeSpl** [comment]
I have done better benchmarks this time, Project1 has about 100 types, Project2 has about 1100 types.

Before this pull request
|    Method |      Mean |    Error |   StdDev | Rank |      Gen 0 |      Gen 1 |     Gen 2 | Allocated |
|---------- |----------:|---------:|---------:|-----:|-----------:|-----------:|----------:|----------:|
|    Project1 |  27.73 ms | 0.113 ms | 0.106 ms |    1 |  3312.5000 |  1656.2500 | 1000.0000 |  18.78 MB |
| Project2 | 674.57 ms | 4.942 ms | 4.381 ms |    2 | 69000.0000 | 25000.0000 | 5000.0000 | 401.78 MB |

After this pull request
|    Method |      Mean |    Error |   StdDev | Rank |      Gen 0 |     Gen 1 |     Gen 2 | Allocated |
|---------- |----------:|---------:|---------:|-----:|-----------:|----------:|----------:|----------:|
|    Project1 |  12.63 ms | 0.185 ms | 0.173 ms |    1 |   703.1250 |  328.1250 |         - |   4.21 MB |
| Project2 | 389.15 ms | 4.325 ms | 4.046 ms |    2 | 14000.0000 | 6000.0000 | 2000.0000 |  81.97 MB |

**Comment by BenMorris** [comment]
Thanks for this, but it is an enormous pull request!

The problem with large pull requests is that they place a burden on the person who has to review them. They also tend to mix up concerns - there's some valuable functional improvements here, but I'll have to accept a major re-wiring of the internals to accept them.

Performance improvements are always welcome, but IMHO there's a point where code is "good enough". Bear in mind that NetArchTest is designed to run in code production pipelines. We want to keep this stuff lightweight, of course, but there was some excellent work on dependency search in #36 that baked performance thresholds into our unit tests.

Given that there has been a build up of new features (especially on extensibility) I will get a release out over the next few days, probably without this pull request. Once I've had the time to fully review this and understand the changes we can look get another release out that includes these functional improvements.

**Comment by NeVeSpl** [comment]
Sure, take your time, but if I may suggest something, start from looking at the end, how final code looks like. Some middle steps look really scary, and some ideas have come and gone through the way, but the final result is really nice, and the core classes: DependencySearch, SearchDefinition, TypeDefinitionCheckingContext are now much simpler and easier to reason about.

**Comment by tibel** [comment]
Hmm, maybe this could be split in multiple small pull request for reviewing.

**Comment by sm-g** [comment]
`(Not)HaveDependencyOn` is useless without fixes from this PR, isn't it? We cannot rely on its results at current implementation, so we *should not* use then in our tests at all.

**Comment by BenMorris** [comment]
Right - I'm *finally* ready to pull this bad boy in. I like the new structure to dependency searches and it fixes a lot of long-standing problems. I've checked that it doesn't introduce any breaking changes.

The only quibbles I have are relatively minor. For example, `TypeReferenceTree<T>` _might_ be an over-optimisation. No matter. It's great code that improves the library. 

Thanks for all the work.

**Comment by sm-g** [comment]
When you plan to update nuget package?

**Pull request merged**
